spring:
  main:
    banner:
      mode: off
  threads:
    virtual:
      enabled: true

custom:
  prop1: value1
  prop2: value2

custom-strings:
  - "list value 1"
  - "list-value-2"

endpoints:
  enabled: false