sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

install: true

before_script:
  - docker --version
  - docker-compose --version

script:
  - mvn clean install --batch-mode -P run-in-ci
