server:
  port: 8180

spring:
  datasource:
    url: jdbc:postgresql://localhost:${postgresql.db.port:5432}/myuser
    username: myuser
    password: superpassword
    driver:
      class:
        name: org.postgresql.Driver