server:
  port: 8180

app:
  datasource:
    hikari:
      jdbc-url: "${APP_DATASOURCE_HIKARI_JDBC_URL:jdbc:postgresql://localhost:15432/myuser}"
      username: "${APP_DATASOURCE_HIKARI_USERNAME:myuser}"
      password: "${APP_DATASOURCE_HIKARI_PASSWORD:superpassword}"
      maximum-pool-size: 30
      driver:
        class:
          name: org.postgresql.Driver
  openapi:
    url: "http://localhost:8180"
  cors:
    origins: "http://localhost:8180,http://localhost:3000"

springdoc:
  api-docs:
    enabled: true

thirdparty:
  ping:
    url: "http://www.example.com"