server:
  port: 8180

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/myuser
    username: myuser
    password: superpassword
    driver:
      class:
        name: org.postgresql.Driver

app:
  openapi:
    url: "http://localhost:8180"
  cors:
    origins: "http://localhost:8180,http://localhost:3000"

springdoc:
  api-docs:
    enabled: true

thirdparty:
  ping:
    url: "http://www.example.com"