version: '2'
networks:
  main:

services:
  springboot-jdbc-postgres:
    container_name: springboot-jdbc-postgres
    image: "postgres:10"
    ports:
      - "15432:5432"
    environment:
      - "POSTGRES_USER=myuser"
      - "POSTGRES_PASSWORD=superpassword"
    networks:
      main:
        aliases:
          - springboot-jdbc-postgres