networks:
  main:
    name: my-spring-boot-network

services:
  springboot-jdbc-postgres:
    container_name: springboot-jdbc-postgres
    image: "public.ecr.aws/docker/library/postgres:16"
    ports:
      - "15432:5432"
    environment:
      - "POSTGRES_USER=myuser"
      - "POSTGRES_PASSWORD=superpassword"
    networks:
      main:
        aliases:
          - springboot-jdbc-postgres