server:
  port: ${RANDOM_PORT_5:8185}

custom:
  message1: Message1 from spring-boot-default-config/application.properties
  message2: Message2 from spring-boot-default-config/application.properties
  message3: Message3 from spring-boot-default-config/application.properties
  message4: Message4 from spring-boot-default-config/application.properties
  message5: Message5 from spring-boot-default-config/application.properties