name: 'CI-master'

on:
  push:
    branches:
      - master

jobs:
  master-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # default 360
    steps:
    - uses: actions/checkout@v1
      with:
        ref: 'master'
    - name: Install Java 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        java-package: jdk
        architecture: x64
    - name: Cache maven dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-cache-master-v1
        restore-keys: |
          ${{ runner.os }}-maven-cache-master-v1
    - name: 'Install dependencies'
      run: |
        ./ci-install-dependencies.sh
    - name: 'CI Build Command'
      timeout-minutes: 20
      run: |
        ./ci-build.sh
    - name: Archive cucumber reports 1
      uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: cucumber-test-result-1
        path: RestExample/RestServiceAndConsumerBddTest/target/cucumber-html-report
    - name: Archive cucumber reports 2
      uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: cucumber-test-result-2
        path: RestExample/RestServiceAndConsumerBddTestWithMocks/target/cucumber-html-report